# Generated by Django 4.2.4 on 2024-04-27 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BloodLevel',
            fields=[
                ('bloodlevelId', models.AutoField(primary_key=True, serialize=False)),
                ('blood_category', models.CharField(max_length=100)),
                ('percentage_value', models.FloatField()),
            ],
        ),
    ]
